In [1]:
# Add a command to produce plots directly below cells.
%matplotlib inline
# Import required packages.
import numpy as np
import os
# Import xarray and glob for data analysis.
import xarray as xr
from glob import glob
# Dask for processing.
import dask as da

os.chdir("/home/561/gp8431")
from climate import StandardGrid
from climate import Projection

import matplotlib.pyplot as plt

import matplotlib as mpl

# Change working directory.
os.chdir("/scratch/w40/gp8431/run")


In [2]:
def local_heating(heat_type, heat_val, plev, lon_min, lon_max, lat_min, lat_max, lon_cen):
    heating = xr.open_dataset("/scratch/w40/gp8431/run/"+heat_type+"_amp_"+heat_val+"/plevel_avg_"+heat_type+".nc", decode_times = False).local_heating
    heat_slice = heating.sel(lat=slice(lat_min, lat_max), lon=slice(lon_min, lon_max), pfull=plev)
    heat_peak = heating.sel(lat=0.0, lon=lon_cen, pfull=plev, method="nearest")
    return heating, heat_slice, heat_peak

In [3]:
gc, gc_slice, gc_peak = local_heating('gh', '-10.0',300.0, 85., 105., -10., 10., 95.)

In [4]:
ic, ic_slice, ic_peak = local_heating('ih', '-10.0',925.0, 85., 105., -10., 10., 95.)

In [5]:
gh, gh_slice, gh_peak = local_heating('gh', '10.0', 300.0, 50., 70., -10., 10., 60.)

In [6]:
ih, ih_slice, ih_peak = local_heating('ih', '10.0', 925.0, 50., 70., -10., 10., 60.)

In [7]:
gc_peak

<xarray.DataArray 'local_heating' (time: 1)>
array([-0.000114], dtype=float32)
Coordinates:
    lon      float64 95.62
    lat      float64 1.395
    pfull    float32 300.0
  * time     (time) float64 750.0
Attributes:
    long_name:      Local heating (deg/sec)
    units:          deg/sec
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT

In [8]:
gh_peak

<xarray.DataArray 'local_heating' (time: 1)>
array([0.000114], dtype=float32)
Coordinates:
    lon      float64 59.06
    lat      float64 1.395
    pfull    float32 300.0
  * time     (time) float64 750.0
Attributes:
    long_name:      Local heating (deg/sec)
    units:          deg/sec
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT

In [9]:
ic_peak

<xarray.DataArray 'local_heating' (time: 1)>
array([-5.715734e-05], dtype=float32)
Coordinates:
    lon      float64 95.62
    lat      float64 1.395
    pfull    float32 925.0
  * time     (time) float64 750.0
Attributes:
    long_name:      Local heating (deg/sec)
    units:          deg/sec
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT

In [10]:
ih_peak

<xarray.DataArray 'local_heating' (time: 1)>
array([6.006596e-05], dtype=float32)
Coordinates:
    lon      float64 59.06
    lat      float64 1.395
    pfull    float32 925.0
  * time     (time) float64 750.0
Attributes:
    long_name:      Local heating (deg/sec)
    units:          deg/sec
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT

<xarray.DataArray 'pfull' (pfull: 21)>
array([1000.,  925.,  850.,  700.,  600.,  500.,  400.,  300.,  250.,  200.,
        150.,  100.,   70.,   50.,   30.,   20.,   10.,    5.,    3.,    2.,
          1.], dtype=float32)
Coordinates:
  * pfull    (pfull) float32 1000.0 925.0 850.0 700.0 600.0 ... 5.0 3.0 2.0 1.0
Attributes:
    units:           hPa
    long_name:       pressure
    cartesian_axis:  Z
    axis:            Z
    positive:        down